---
title: "Sustainable Indicators"
description: |
  Some additional details about the website
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
repository_url: https://github.com/LF2L/everest-bio
bibliography: 01-Sustainable-indicators.bib
nocite: '@*'
---


# Abstract

Recycling is key strategy in order to establish in the circular economy umbrella concept.  
What are the the 'pertinent' indicators to evaluate the local distributed recycling network in a perspective of revelance of and also in the quality and feasability to obtain data.

Quels indicateurs pour évaluer la soutenabilité : pertinence, disponibilité, facilité de mise en œuvre ; s’accorcher au territoire : analyse des enjeux du territoire (périmètre thèse pavlo) => interview des acteurs, collecte d’info sur le territoire => impact quels sont les enjeux ? quels sont les indicateurs que l’on peut associer et les méthodes d’évaluation associée avec Nadège, Mauricio et Hakim 


# Rationale

## LCA and 3D Printing

- AM’s environmental performance is seldom investigated [@Saade2020].



## LCA and Social practices

- Llinks social practices to the life cycle inventory of LCA [@Suski2020].