---
title: "Literature review on Ecosystem services for Distributed Recycling"
output:
  html_document:
    toc: no
    toc_float: yes
    keep_md: yes
permalink: /competences/
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
library(tidyverse)
library(revtools)

```



## Initial database for Screening

```{r Screening.ES-Rec-Plast }
Screening <- read_bibliography("Scopus/ES-Rec-Plast.csv")
# Screening
screen_abstracts(Screening)
```


## Screened
```{r data, include=FALSE}

# Filter the selected documents and changing the names. Made on 30/03 -----
# Reading data
Screened <- read_csv("Scopus/ES-Rec-Plast.csv")

# names(Screened)
# Screened <- Screened %>% filter(screened_abstracts == 'selected') %>% 
#   rename(
#     screened_abstracts_i = screened_abstracts,
#     notes_i = notes
#     )
# write_csv(Screened, file = 'Scopus/ES-Rec-Plast-Screened.csv')


# Re-Screening for selecting the best for Ecosystem Service ----
Screened <- read_bibliography('Scopus/ES-Rec-Plast-Screened.csv')
screen_abstracts(Screened)

Screened$notes
```



```{r}


Screened <- read_bibliography("Scopus/ES-Rec-Plast.csv")
Screened %>% group_by(document_type) %>% tally()
```

