---
title: "Literature review on Ecosystem services for Distributed Recycling"
output:
  html_document:
    toc: no
    toc_float: yes
    keep_md: yes
permalink: /competences/
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
library(tidyverse)
library(revtools)
library(readxl)
```



## Initial database for Screening

```{r Screening.ES-Rec-Plast }
Screening <- read_bibliography("Scopus/ES-Rec-Plast.csv")
# Screening
screen_abstracts(Screening)

```


## Screened
```{r data, include=FALSE}

# Filter the selected documents and changing the names. Made on 30/03 -----
# Reading data
Screened <- read_csv("Scopus/ES-Rec-Plast.csv")

names(Screened)
Screened <- Screened %>% filter(screened_abstracts == 'selected') %>%
  rename(
    screened_abstracts_i = screened_abstracts,
    notes_i = notes
    )
#write_csv(Screened, file = 'Scopus/ES-Rec-Plast-Screened.csv')
# ---- Document exported on 19 July ---
# write_csv(Screened %>% select(label,title, abstract, doi, notes_i) , "Scopus/Screened-WD.csv")

names(Screened)

# Re-Screening for selecting the best for Ecosystem Service ----
Screened <- read_bibliography('Scopus/ES-Rec-Plast-Screened.csv')
screen_abstracts(Screened)

Screened$notes
```


## CICES V 5.1


```{r}
library(readxl)
library(here)
library(yaml)
library(xlsx)
library(tidyverse)

CICES <- read_excel(here("CICES/Finalised-V5.1_18032018.xlsx"), sheet = "CICES V5.1",  skip = 4 )
names(CICES)

Test <- CICES %>% select(Division, Group, Class, Code, `Class type`, `Simple descriptor`)
#write_yaml(V1, "GF/CICES-GF.yml")

# Ordering the Factors
Test <- Test %>%
  mutate(Division = factor(Division, Test %>% pull(Division) %>% unique())) %>% 
  mutate(Group = factor(Group, Test %>% pull(Group) %>% unique())) 

Divisiones <- Test$Division %>% levels()
Grupos <- Test$Group %>% levels()


Total_preguntas <- Test %>% group_by(Division,Group) %>% tally()
#Encuesta <- list(Test$Division %>% levels())
```


```{r}
# Biomass
Preguntas <- 
  Test %>% 
  filter(Division == Divisiones[4]) %>% 
  filter(Group == Grupos[11]) 
Preguntas

paste(Preguntas$`Code`, Preguntas$`Simple descriptor`, sep = ", ")

```

