---
title: "Ramdom ideas"
output: html_document
---

From a supply chain perspective, the feasibility evaluation for the establishment of recycling networks should be oriented towards sustainable development. 
In addition, the notion of sustainability could be used as a framework to analyze and manage the impact of human activities (or supply chain) on ecosystem services [@Abson2014].
A network is sustainable, if it integrates the economic, environmental and social dimensions, traditionally referred to as the three pillars of sustainability (’triple bottom-lines - TBL) (Hacking and Guthrie, 2008). 
In addition, @Bautista2016 proposes the integration of political and technological dimensions (TBL+) if they have a great importance in the system to evaluate.. However, literature reviews about supply chains networks highlight : 
(1) the little consideration of social, technological and political aspects in sustainability assessments, and 
(2) the great consideration of economic and environmental aspects 
[@EspinozaPerez2017c, @Fonseca2018, @Moreno-Camacho2019]. 


