---
title: "Towards a robust desicion tool for ecosystems services in the industrial systems:  A case study of Distributed recycling for additive manufacturing"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PPSQ

<!-- Problem -->
Ecosystem services is a powerful conceptual framework to put in evidence the benefits that humans received from nature, most of time for free.
The problem is that it is complex to link between the local ecosystem services of a territory and the industrial systems placed in it to identify the interactions (as synergy and impacts) with the purpose to create strong sustainability.
From a decision-maker  perspective, there is no a aide decision tool to guide towards a  techno-ecological evaluation of the development of industrial systems in a territory.
<!-- Knowledge Gap -->
There have been major efforts in the valuation of ES given by ecosystems (terrestial,aquatic, atmospheric) to the human well-being. 
Likewise, LCA thinking have putting major attention in the impact of industrial filières to the environmental aspect. 
Nevertheless, few researches have been addressed in aligning the territorial priorities in terms of ES for planning and urban development with the supply/demand of ES by industrial systems, particularity for design industrial landscapes that include the ES in the early-design phases of conception. 
<!-- Context -->
The technical advancements of recycling approaches using additive manufacturing are promising technical intervations to foster plastic recycling at a local level.

<!-- Logic & Evidence for Problem, KG and Context -->



<!-- Conceptual Framework -->
The use of 

<!-- Purpose -->
The purpose of this article is to propose a methodological to prioritize ecosystem services in regarding the territorial and industrial priotities. 
This prioritazation is the firs istep to create techno-ecological sinergies between ecological and industrial systems
<!-- Reseacch Questions -->
- 


