---
title: "Literature review on Ecosystem services for Distributed Recycling"
output:
  html_document:
    toc: no
    toc_float: yes
    keep_md: yes
permalink: /competences/
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
library(tidyverse)
library(revtools)
library(readxl)
```



## Initial database for Screening

```{r Screening.ES-Rec-Plast }
Screening <- read_bibliography("Scopus/ES-Rec-Plast.csv")
# Screening
screen_abstracts(Screening)

```


## Screened
```{r data, include=FALSE}

# Filter the selected documents and changing the names. Made on 30/03 -----
# Reading data
Screened <- read_csv("Scopus/ES-Rec-Plast.csv")

names(Screened)
Screened <- Screened %>% filter(screened_abstracts == 'selected') %>%
  rename(
    screened_abstracts_i = screened_abstracts,
    notes_i = notes
    )
#write_csv(Screened, file = 'Scopus/ES-Rec-Plast-Screened.csv')
# ---- Document exported on 19 July ---
# write_csv(Screened %>% select(label,title, abstract, doi, notes_i) , "Scopus/Screened-WD.csv")

names(Screened)

# Re-Screening for selecting the best for Ecosystem Service ----
Screened <- read_bibliography('Scopus/ES-Rec-Plast-Screened.csv')
screen_abstracts(Screened)

Screened$notes
```


## CICES V 5.1


```{r}
library(readxl)
library(here)
library(yaml)
library(xlsx)
library(tidyverse)

CICES <- read_excel(here("CICES/Finalised-V5.1_18032018.xlsx"), sheet = "CICES V5.1",  skip = 4 )
names(CICES)

#CICES <- CICES %>% select(Filter, Section, Division, Group, Class, Code, `Class type`, `Simple descriptor`)

#Test <- tibble(CICES = Test %>% pull(Group) %>% unique())
#write_yaml(V1, "GF/CICES-GF.yml")

# Ordering the Factors
CICES <- 
  CICES %>%
  mutate(Section = factor(Section, CICES %>% pull(Section) %>% unique())) %>% 
  mutate(Division = factor(Division, CICES %>% pull(Division) %>% unique())) %>% 
  mutate(Group = factor(Group, CICES %>% pull(Group) %>% unique())) %>% 
  mutate(Section = 
           factor(Section, 
            c("Provisioning (Biotic)", "Provisioning (Abiotic)",
            "Regulation & Maintenance (Biotic)", "Regulation & Maintenance (Abiotic)",
            "Cultural (Biotic)", "Cultural (Abiotic)") ))

Cuestionario <- list()

Cuestionario$Industrial <- 
  CICES %>% group_by(Section,Group) %>% 
  tally()


CICES %>%
  filter(Code %in% c("1.1.1.1", "1.1.1.2", "1.1.1.3")) 
  
  
# Identifying the codes
Test <- 
CICES %>%
  group_by(Group) %>%
  #arrange(stopSequence) %>%
  filter(row_number()==1 | row_number()==n())


library(readxl)
library(here)
library(flextable)



ft_1 <- flextable(data_ex)
ft_1 <- theme_box(ft_1)
ft_2 <- merge_v(ft_1, j = "srdr_id",
  target = c("srdr_id", "substances"))
  ft_2
  
CICES %>% select(Group, Class, Code) %>% 
  filter(Code %in% c("1.1.1.1", "1.1.1.2", "1.1.1.3")) %>% 
  flextable() %>% 
  merge_v( j = "Group")
  
  kbl(caption = "ES for Food Nutrition") %>%
  collapse_rows(columns = 1:1) 

library(dplyr)
library(flextable)

devtools::install_github("haozhu233/kableExtra")

collapse_rows_dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
                 C2 = c(rep("c", 7), rep("d", 3), rep("c", 2), rep("d", 3)),
                 C3 = 1:15,
                 C4 = sample(c(0,1), 15, replace = TRUE))
kbl(collapse_rows_dt, align = "c") %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")

Divisiones <- CICES$Division %>% levels()
Grupos <- Test$Group %>% levels()


Total_preguntas <- CICES %>% group_by(Section,Group) %>% tally()
#Encuesta <- list(Test$Division %>% levels())
```


```{r}
# Biomass
Preguntas <- 
  Test %>% 
  filter(Division == Divisiones[4]) %>% 
  filter(Group == Grupos[11]) 
Preguntas

paste(Preguntas$`Code`, Preguntas$`Simple descriptor`, sep = ", ")

```

